name: Salesforce Code Analysis & Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Install SFDX Scanner
        run: |
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run Static Code Analysis
        run: |
          sfdx scanner run --format html --target "force-app/main/default/classes,force-app/main/default/triggers,force-app/main/default/lwc" --outfile code-analysis-report.html

      - name: Upload Code Analysis Report
        uses: actions/upload-artifact@v3
        with:
          name: code-analysis-report
          path: code-analysis-report.html

      - name: Fail on Security Issues
        run: |
          if grep -q "Security" code-analysis-report.html; then
            echo "Security issues found. Failing the build."
            exit 1
          fi

  apex-tests:
    name: Run Apex Tests & Code Coverage
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Authenticate Salesforce Org
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > authfile.json
          sfdx auth:sfdxurl:store -f authfile.json -s -a test-org

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run --resultformat human --codecoverage --outputdir test-results

      - name: Check Code Coverage
        run: |
          COVERAGE=$(grep -oP '(?<=Total Coverage: )[0-9]+' test-results/test-run-id.txt)
          echo "Code coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 75 ]; then
            echo "Code coverage below 75%. Failing build."
            exit 1
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
