name: Salesforce Code Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Install SFDX Scanner
        run: |
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run Static Code Analysis
        run: |
          sfdx scanner run --format html --target "force-app/main/default/classes,force-app/main/default/triggers,force-app/main/default/lwc" --outfile code-analysis-report.html

      - name: Upload Code Analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-report
          path: code-analysis-report.html

      - name: Fail on Security Issues
        run: |
          if grep -q "Security" code-analysis-report.html; then
            echo "Security issues found. Failing the build."
            exit 1
          fi
