name: Salesforce Code Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Install SFDX Scanner
        run: |
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run PMD for Apex Code
        run: |
          sfdx scanner run --engine pmd --target "force-app/main/default/classes,force-app/main/default/triggers" --format html --outfile pmd-report.html

      - name: Install ESLint
        run: |
          npm install -g eslint

      - name: Run ESLint for LWC
        run: |
          eslint force-app/main/default/lwc --ext .js --format html -o eslint-report.html || true

      - name: Upload Code Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-reports
          path: |
            pmd-report.html
            eslint-report.html

      - name: Fail on Security Issues
        run: |
          if grep -q "Security" pmd-report.html || grep -q "error" eslint-report.html; then
            echo "Security or LWC linting issues found. Failing the build."
            exit 1
          fi
